/**
 * These tests read the real artifact rather than a fixture: the point of the
 * pipeline is that it agrees with the delivered atlas, and a fixture would only
 * prove the importer agrees with itself.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { SPEC_DIR, TYPES_DIR } from './lib/paths.js';

const spec = (name: string): unknown =>
  JSON.parse(readFileSync(join(SPEC_DIR, 'atlas', name), 'utf8'));

describe('generated atlas spec', () => {
  it('carries every form the atlas declares', () => {
    expect(spec('forms.json')).toHaveLength(376);
  });

  it('matches the counts the audit states about the atlas', () => {
    expect(spec('transitions.json')).toHaveLength(1672);
    expect(spec('journeys.json')).toHaveLength(66);
    expect(spec('requirements.json')).toHaveLength(91);
    expect(spec('qa-scenarios.json')).toHaveLength(2440);
    expect(spec('lifecycles.json')).toHaveLength(19);
    expect(spec('diagrams.json')).toHaveLength(11);
  });

  it('pins the atlas digests, so a swapped artifact is visible in the diff', () => {
    const meta = spec('meta.json') as { graphDigest: string; contentDigest: string };
    expect(meta.graphDigest).toBe(
      '693910e40ffca85b30d9eafd05c2bb7d59934da966c10afdafa5afe6e51fe7df',
    );
    expect(meta.contentDigest).toBe(
      'ceace6ea95167e81b8cbbd86670930270b0b177e81db07e8e0fa437d21747a5c',
    );
  });

  it('closes the transition graph over the form catalogue', () => {
    const ids = new Set((spec('forms.json') as { id: string }[]).map((f) => f.id));
    const dangling = (spec('transitions.json') as { from: string; to: string }[]).filter(
      (t) => !ids.has(t.from) || !ids.has(t.to),
    );
    expect(dangling).toEqual([]);
  });

  it('distributes forms across the 16 domains exactly as the atlas counts them', () => {
    const byDomain = new Map<string, number>();
    for (const form of spec('forms.json') as { domain: string }[]) {
      byDomain.set(form.domain, (byDomain.get(form.domain) ?? 0) + 1);
    }
    expect(byDomain.size).toBe(16);
    expect(byDomain.get('Боевая ситуация')).toBe(73);
    expect(byDomain.get('Создание локального персонажа')).toBe(44);
    expect(byDomain.get('Настройки')).toBe(6);
    expect([...byDomain.values()].reduce((a, b) => a + b, 0)).toBe(376);
  });
});

describe('generated atlas types', () => {
  const source = readFileSync(join(TYPES_DIR, 'atlas.ts'), 'utf8');

  it('is marked as generated so nobody edits it by hand', () => {
    expect(source.startsWith('// Generated by tools/import.')).toBe(true);
  });

  it('uses LF endings regardless of the platform it was generated on', () => {
    expect(source).not.toContain('\r\n');
  });

  it('emits one FormId literal per form', () => {
    // The final member carries the closing semicolon, so it must be optional
    // here — matching only `"` would silently drop the last literal.
    const union = /export type FormId =\n((?: {2}\| "[^"]+";?\n)+)/.exec(source);
    expect(union).not.toBeNull();
    expect(union![1]!.trimEnd().split('\n')).toHaveLength(376);
  });

  it('maps every domain to the src/web/forms folder that owns it', () => {
    expect(source).toContain('"Боевая ситуация": "CMB"');
    expect(source).toContain('"Приложение и локальные данные": "APP"');
  });
});
