/**
 * Pinned against the registry's own control sheet: 16 canonical species,
 * 17 statblocks (Bubuy carries two variants), 119 stat rows (17 × 7), and the
 * 16 embedded artworks the audit counts as CHK-011.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { MEDIA_DIR, SPEC_DIR, TYPES_DIR } from './lib/paths.js';

const spec = <T>(name: string): T =>
  JSON.parse(readFileSync(join(SPEC_DIR, 'bestiary', name), 'utf8')) as T;

interface Species {
  'Species ID': string;
  'Art asset key': string;
}
interface Art {
  speciesId: string;
  artAssetKey: string;
  file: string;
  bytes: number;
}

const species = spec<Species[]>('species.json');
const arts = spec<Art[]>('arts.json');

describe('generated bestiary spec', () => {
  it('carries 16 species and 17 statblocks', () => {
    expect(species).toHaveLength(16);
    expect(spec<unknown[]>('templates.json')).toHaveLength(17);
  });

  it('carries 119 stat rows, the 17 x 7 the control sheet states', () => {
    expect(spec<unknown[]>('stats.json')).toHaveLength(119);
  });

  it('carries the remaining catalogues at their declared sizes', () => {
    expect(spec<unknown[]>('anatomy.json')).toHaveLength(20);
    expect(spec<unknown[]>('attacks.json')).toHaveLength(22);
    expect(spec<unknown[]>('rules.json')).toHaveLength(80);
    expect(spec<unknown[]>('symbiont-relations.json')).toHaveLength(13);
    expect(spec<unknown[]>('zone-routing.json')).toHaveLength(20);
    expect(spec<unknown[]>('attack-contracts.json')).toHaveLength(22);
  });

  it('resolves every template against a known species', () => {
    const ids = new Set(species.map((s) => s['Species ID']));
    const templates = spec<{ 'Species ID': string }[]>('templates.json');
    expect(templates.filter((t) => !ids.has(t['Species ID']))).toEqual([]);
  });

  it('resolves every rule row against the Executable Rules catalogue', () => {
    const catalogue = new Set(
      (
        JSON.parse(readFileSync(join(SPEC_DIR, 'rules', 'rules.json'), 'utf8')) as {
          'Rule ID': string;
        }[]
      ).map((r) => r['Rule ID']),
    );
    const rows = spec<{ 'Rule ID': string }[]>('rules.json');
    expect(rows.filter((r) => !catalogue.has(r['Rule ID']))).toEqual([]);
  });

  it('records the gate, its one section header, and what was skipped', () => {
    const meta = spec<{ gateAllPass: boolean; skippedSheets: string[] }>('meta.json');
    expect(meta.gateAllPass).toBe(true);
    // Both spread a title across every column, so their headers carry duplicate
    // names; the gallery is a picture grid rather than rows.
    expect(meta.skippedSheets).toEqual(['00_Сводка', '01_Галерея']);
  });
});

describe('extracted arts', () => {
  const dir = join(MEDIA_DIR, 'bestiary');
  const files = readdirSync(dir);

  it('writes one artwork per species (CHK-011)', () => {
    expect(arts).toHaveLength(16);
    expect(files).toHaveLength(16);
    expect(new Set(arts.map((a) => a.speciesId)).size).toBe(16);
  });

  it('matches each art to the key the species sheet declares', () => {
    // The gallery is a two-column grid, so an art is paired with the caption
    // below it in its own column; that result is then checked against
    // 02_Виды/"Art asset key" before anything is written.
    const declared = new Map(species.map((s) => [s['Species ID'], s['Art asset key']]));
    for (const art of arts) {
      expect(declared.get(art.speciesId)).toBe(art.artAssetKey);
      expect(art.file).toBe(`${art.artAssetKey.toLowerCase()}.jpeg`);
    }
  });

  it('covers every species, leaving none without art', () => {
    const withArt = new Set(arts.map((a) => a.speciesId));
    expect(species.filter((s) => !withArt.has(s['Species ID']))).toEqual([]);
  });

  it('writes real JPEG bytes', () => {
    for (const file of files) {
      const bytes = readFileSync(join(dir, file));
      expect(bytes[0]).toBe(0xff);
      expect(bytes[1]).toBe(0xd8);
      expect(bytes[2]).toBe(0xff);
      expect(bytes.byteLength).toBeGreaterThan(10_000);
    }
  });
});

describe('generated bestiary types', () => {
  const source = readFileSync(join(TYPES_DIR, 'bestiary.ts'), 'utf8');

  it('emits a SpeciesId per species and a template id per statblock', () => {
    const speciesUnion = /export type SpeciesId =\n((?: {2}\| "[^"]+";?\n)+)/.exec(source);
    expect(speciesUnion![1]!.trimEnd().split('\n')).toHaveLength(16);

    const templateUnion = /export type CanonicalTemplateId =\n((?: {2}\| "[^"]+";?\n)+)/.exec(
      source,
    );
    expect(templateUnion![1]!.trimEnd().split('\n')).toHaveLength(17);
  });

  it('is marked generated and uses LF endings', () => {
    expect(source.startsWith('// Generated by tools/import.')).toBe(true);
    expect(source).not.toContain('\r\n');
  });
});
