/**
 * Pinned against the control values the artifacts state: CHK-007 payload 1144,
 * CHK-008 QA 51, atlas `counts.automatedAbilities` 167, RTC-007 seven stats.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { SPEC_DIR, TYPES_DIR } from './lib/paths.js';

const spec = <T>(name: string): T =>
  JSON.parse(readFileSync(join(SPEC_DIR, 'character', name), 'utf8')) as T;

describe('generated character spec', () => {
  it('carries the full payload catalogue (CHK-007)', () => {
    expect(spec<unknown[]>('payloads.json')).toHaveLength(1144);
  });

  it('carries the QA scenarios the audit counts (CHK-008)', () => {
    expect(spec<unknown[]>('qa.json')).toHaveLength(51);
  });

  it('carries 167 abilities, the figure the atlas states', () => {
    expect(spec<unknown[]>('abilities.json')).toHaveLength(167);
  });

  it('carries seven stats, matching the generator contract RTC-007', () => {
    expect(spec<unknown[]>('stats.json')).toHaveLength(7);
  });

  it('carries the remaining catalogues at their declared sizes', () => {
    expect(spec<unknown[]>('races.json')).toHaveLength(3);
    expect(spec<unknown[]>('classes.json')).toHaveLength(3);
    expect(spec<unknown[]>('skills.json')).toHaveLength(45);
    expect(spec<unknown[]>('symbionts.json')).toHaveLength(74);
    expect(spec<unknown[]>('symbiont-levels.json')).toHaveLength(144);
    expect(spec<unknown[]>('development-nodes.json')).toHaveLength(182);
    expect(spec<unknown[]>('ability-contexts.json')).toHaveLength(334);
    expect(spec<unknown[]>('runtime-contracts.json')).toHaveLength(71);
    expect(spec<unknown[]>('operations.json')).toHaveLength(16);
  });

  it('resolves every rule-trace row against the Executable Rules catalogue', () => {
    const rules = JSON.parse(readFileSync(join(SPEC_DIR, 'rules', 'rules.json'), 'utf8')) as {
      'Rule ID': string;
    }[];
    const catalogue = new Set(rules.map((r) => r['Rule ID']));
    const trace = spec<{ 'Rule ID': string }[]>('rule-trace.json');

    expect(trace).toHaveLength(291);
    expect(trace.filter((t) => !catalogue.has(t['Rule ID']))).toEqual([]);
  });

  it('records that both self-checks passed and names what was deferred', () => {
    const meta = spec<{ gatesAllPass: boolean; deferredSheets: string[] }>('meta.json');
    expect(meta.gatesAllPass).toBe(true);
    // The XP runtime sheet is stacked sections, not one table; it needs its own
    // reader. Leaving it out must stay visible rather than quietly forgotten.
    expect(meta.deferredSheets).toEqual(['24_XP_Runtime']);
  });
});

describe('generated character types', () => {
  const source = readFileSync(join(TYPES_DIR, 'character.ts'), 'utf8');

  it('emits a StatCode per stat', () => {
    const union = /export type StatCode =\n((?: {2}\| "[^"]+";?\n)+)/.exec(source);
    expect(union).not.toBeNull();
    expect(union![1]!.trimEnd().split('\n')).toHaveLength(7);
  });

  it('emits an AbilityId per ability', () => {
    const union = /export type AbilityId =\n((?: {2}\| "[^"]+";?\n)+)/.exec(source);
    expect(union).not.toBeNull();
    expect(union![1]!.trimEnd().split('\n')).toHaveLength(167);
  });

  it('exposes the payload entity kinds', () => {
    expect(source).toContain('export type CharacterEntityKind');
    expect(source).toContain('"SYMBIONT_SPECIES"');
    expect(source).toContain('"XP_RACE_POLICY"');
  });

  it('uses LF endings and is marked generated', () => {
    expect(source.startsWith('// Generated by tools/import.')).toBe(true);
    expect(source).not.toContain('\r\n');
  });
});
