/**
 * Pinned against the registry's own control values and the audit: CHK-010
 * counts 64 embedded icons, and the catalogue holds 64 item types.
 */
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { MEDIA_DIR, SPEC_DIR, TYPES_DIR } from './lib/paths.js';

const spec = <T>(name: string): T =>
  JSON.parse(readFileSync(join(SPEC_DIR, 'items', name), 'utf8')) as T;

interface Icon {
  ItemTypeID: string;
  FileName: string;
  VisualStatus: string;
}

describe('generated items spec', () => {
  it('carries 64 item types and 64 icon rows (CHK-010)', () => {
    expect(spec<unknown[]>('catalogue.json')).toHaveLength(64);
    expect(spec<Icon[]>('icons.json')).toHaveLength(64);
  });

  it('carries the profile and formula sheets at their declared sizes', () => {
    expect(spec<unknown[]>('weapon-profiles.json')).toHaveLength(27);
    expect(spec<unknown[]>('armor-profiles.json')).toHaveLength(8);
    expect(spec<unknown[]>('pharmaceuticals.json')).toHaveLength(14);
    expect(spec<unknown[]>('formulas.json')).toHaveLength(22);
    expect(spec<unknown[]>('formula-ranges.json')).toHaveLength(22);
    expect(spec<unknown[]>('combat-values.json')).toHaveLength(65);
    expect(spec<unknown[]>('operations.json')).toHaveLength(29);
  });

  it('resolves every rule-trace row against the Executable Rules catalogue', () => {
    const rules = JSON.parse(readFileSync(join(SPEC_DIR, 'rules', 'rules.json'), 'utf8')) as {
      'Rule ID': string;
    }[];
    const catalogue = new Set(rules.map((r) => r['Rule ID']));
    const trace = spec<{ 'Rule ID': string }[]>('rule-trace.json');

    expect(trace).toHaveLength(157);
    expect(trace.filter((t) => !catalogue.has(t['Rule ID']))).toEqual([]);
  });

  it('records that the control sheet passed in full', () => {
    const meta = spec<{ gateAllPass: boolean; items: number; icons: number }>('meta.json');
    expect(meta.gateAllPass).toBe(true);
    expect(meta.items).toBe(64);
    expect(meta.icons).toBe(64);
  });
});

describe('extracted icons', () => {
  const dir = join(MEDIA_DIR, 'items');
  const files = readdirSync(dir);
  const icons = spec<Icon[]>('icons.json');

  it('writes one file per icon and nothing else', () => {
    expect(files).toHaveLength(64);
    expect(new Set(files)).toEqual(new Set(icons.map((i) => i.FileName)));
  });

  it('names each file as the registry declares, not by media order', () => {
    // xl/media/image10.png sorts before image2.png, so a name-ordered pairing
    // would mis-assign icons without any error surfacing.
    for (const icon of icons) {
      expect(icon.FileName).toBe(`${icon.ItemTypeID.toLowerCase()}.png`);
    }
  });

  it('points every icon at an item that exists in the catalogue', () => {
    const catalogue = new Set(
      spec<{ ItemTypeID: string }[]>('catalogue.json').map((i) => i.ItemTypeID),
    );
    expect(icons.filter((i) => !catalogue.has(i.ItemTypeID))).toEqual([]);
  });

  it('writes real PNG bytes, not truncated or misrouted data', () => {
    const signature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    for (const file of files) {
      const bytes = readFileSync(join(dir, file));
      expect(bytes.subarray(0, 8).equals(signature)).toBe(true);
      expect(bytes.byteLength).toBeGreaterThan(1024);
    }
  });

  it('carries the three visual statuses the data actually uses', () => {
    // The sheet's own preamble describes only TYPE_ALIGNED and
    // PROVISIONAL_VISUAL, but two rows (RES-MAG-001/002) carry a third value,
    // PROVISIONAL_ENTITY, which neither the preamble nor 12_Справочники
    // defines. It is carried through unchanged rather than folded into one of
    // the documented two — see CLAUDE.md, section 4.
    const counts = new Map<string, number>();
    for (const icon of icons) {
      counts.set(icon.VisualStatus, (counts.get(icon.VisualStatus) ?? 0) + 1);
    }
    expect(counts.get('TYPE_ALIGNED')).toBe(52);
    expect(counts.get('PROVISIONAL_VISUAL')).toBe(10);
    expect(counts.get('PROVISIONAL_ENTITY')).toBe(2);
    expect(counts.size).toBe(3);
  });
});

describe('generated items types', () => {
  const source = readFileSync(join(TYPES_DIR, 'items.ts'), 'utf8');

  it('emits an ItemTypeId per catalogued item', () => {
    const union = /export type ItemTypeId =\n((?: {2}\| "[^"]+";?\n)+)/.exec(source);
    expect(union).not.toBeNull();
    expect(union![1]!.trimEnd().split('\n')).toHaveLength(64);
  });

  it('is marked generated and uses LF endings', () => {
    expect(source.startsWith('// Generated by tools/import.')).toBe(true);
    expect(source).not.toContain('\r\n');
  });
});
