/**
 * Checked against the control values the registry and the audit state about
 * themselves (CHK-001 739 cards, CHK-002 699 active), not against a fixture.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { SPEC_DIR, TYPES_DIR } from './lib/paths.js';

const spec = <T>(name: string): T =>
  JSON.parse(readFileSync(join(SPEC_DIR, 'rules', name), 'utf8')) as T;

interface Rule {
  'Rule ID': string;
  Статус: string;
  'Режим реализации': string;
}
interface Link {
  'Source Rule ID': string;
  'Target Rule ID': string;
  'Тип связи': string;
}

const rules = spec<Rule[]>('rules.json');
const ruleIds = new Set(rules.map((r) => r['Rule ID']));

describe('generated rules spec', () => {
  it('carries every rule card (CHK-001)', () => {
    expect(rules).toHaveLength(739);
    expect(ruleIds.size).toBe(739);
  });

  it('splits into 699 active and 40 tombstone (CHK-002)', () => {
    const active = rules.filter((r) => r['Статус'] === 'Активно');
    const tombstone = rules.filter((r) => r['Статус'] === 'Не автоматизируется');
    expect(active).toHaveLength(699);
    expect(tombstone).toHaveLength(40);
    expect(active.length + tombstone.length).toBe(rules.length);
  });

  it('keeps status and implementation mode consistent on every card', () => {
    const pairs = new Map([
      ['Активно', 'Реализовать в игровом ядре'],
      ['Не автоматизируется', 'Не реализовывать в Windows-приложении'],
    ]);
    const mismatched = rules.filter((r) => pairs.get(r['Статус']) !== r['Режим реализации']);
    expect(mismatched).toEqual([]);
  });

  it('carries the parameter, link and source rows the registry declares', () => {
    expect(spec<unknown[]>('parameters.json')).toHaveLength(4621);
    expect(spec<unknown[]>('links.json')).toHaveLength(876);
    expect(spec<unknown[]>('sources.json')).toHaveLength(739);
    expect(spec<unknown[]>('dictionaries.json')).toHaveLength(250);
  });

  it('closes the link graph over the rule catalogue', () => {
    const dangling = spec<Link[]>('links.json').filter(
      (l) => !ruleIds.has(l['Source Rule ID']) || !ruleIds.has(l['Target Rule ID']),
    );
    expect(dangling).toEqual([]);
  });

  it('points every parameter at a rule that exists', () => {
    const orphans = spec<{ 'Rule ID': string }[]>('parameters.json').filter(
      (p) => !ruleIds.has(p['Rule ID']),
    );
    expect(orphans).toEqual([]);
  });

  it('records that the registry control sheet passed in full', () => {
    const meta = spec<{ controlRows: number; controlAllPass: boolean }>('meta.json');
    expect(meta.controlRows).toBe(99);
    expect(meta.controlAllPass).toBe(true);
  });
});

describe('generated rules types', () => {
  const source = readFileSync(join(TYPES_DIR, 'rules.ts'), 'utf8');

  it('emits one RuleId literal per card', () => {
    const union = /export type RuleId =\n((?: {2}\| "[^"]+";?\n)+)/.exec(source);
    expect(union).not.toBeNull();
    expect(union![1]!.trimEnd().split('\n')).toHaveLength(739);
  });

  it('exposes tombstones as their own set, so refusals are explicit', () => {
    const block = /export const TOMBSTONE_RULE_IDS: readonly RuleId\[\] = \[\n(.*?)\n\];/s.exec(
      source,
    );
    expect(block).not.toBeNull();
    expect(block![1]!.trim().split('\n')).toHaveLength(40);
  });

  it('exposes the active set', () => {
    const block = /export const ACTIVE_RULE_IDS: readonly RuleId\[\] = \[\n(.*?)\n\];/s.exec(
      source,
    );
    expect(block).not.toBeNull();
    expect(block![1]!.trim().split('\n')).toHaveLength(699);
  });

  it('keeps link kinds verbatim rather than collapsing near-synonyms', () => {
    // The registry spells these separately; the importer must not merge them.
    expect(source).toContain('"Уточняет / имеет приоритет"');
    expect(source).toContain('"уточняет"');
  });

  it('uses LF endings and is marked generated', () => {
    expect(source.startsWith('// Generated by tools/import.')).toBe(true);
    expect(source).not.toContain('\r\n');
  });
});
