/**
 * Deterministic output.
 *
 * M1 requires the pipeline to be byte-reproducible: the same artifacts must
 * produce the same `generated/` on every run and on every machine. That rules
 * out anything order- or environment-dependent, so everything written here goes
 * through one serialiser with sorted keys, fixed indentation and LF endings.
 * No timestamps, no host names, no run ids.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { JsonObject, JsonValue } from './json.js';

/**
 * JSON with object keys sorted. Arrays keep their order — for atlas data that
 * order is meaningful (it is the order the artifact declares).
 *
 * `undefined` values are dropped rather than serialised: they would vanish in
 * `JSON.stringify` anyway, and removing them here keeps the sorted key list
 * honest about what actually lands in the file.
 */
function sortKeys(value: JsonValue): JsonValue {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value !== null && typeof value === 'object') {
    const out: JsonObject = {};
    for (const key of Object.keys(value).sort()) {
      const item = value[key];
      if (item === undefined) continue;
      out[key] = sortKeys(item);
    }
    return out;
  }
  return value;
}

export function stringify(value: JsonValue): string {
  return JSON.stringify(sortKeys(value), null, 2) + '\n';
}

/** Header stamped on every generated file. Deliberately free of run metadata. */
export function banner(source: string): string {
  return [
    '// Generated by tools/import. Do not edit by hand — see CLAUDE.md.',
    `// Source: ${source}`,
    '',
  ].join('\n');
}

export async function writeJson(path: string, value: JsonValue): Promise<number> {
  const text = stringify(value);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, text, 'utf8');
  return Buffer.byteLength(text, 'utf8');
}

export async function writeText(path: string, text: string): Promise<number> {
  const normalised = text.replace(/\r\n/g, '\n');
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, normalised, 'utf8');
  return Buffer.byteLength(normalised, 'utf8');
}

/** Quotes a string for embedding in generated TypeScript. */
export function tsLiteral(value: string): string {
  return JSON.stringify(value);
}

/**
 * A union type alias, or `never` when the set is empty — an empty union is a
 * real signal that the source had nothing, and `never` makes downstream code
 * fail to compile rather than silently accept anything.
 */
export function tsUnion(name: string, members: readonly string[], doc?: string): string {
  const body = members.length === 0 ? 'never' : members.map(tsLiteral).join('\n  | ');
  const comment = doc === undefined ? '' : `/** ${doc} */\n`;
  return members.length === 0
    ? `${comment}export type ${name} = never;\n`
    : `${comment}export type ${name} =\n  | ${body};\n`;
}
